version: 0.0
Resources:
- TargetService:
Type: AWS::ECS::Service
Properties:
TaskDefinition: "arn:aws:ecs:us-east-1:156962844638:task-definition/pms-penstionman-rep-TD:1"
LoadBalancerInfo:
ContainerName: "pms-penstionman-rep-CNT"
ContainerPort: 9000
PlatformVersion: "LATEST"
